name: CICD Build - Javelin Ramparts Server

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*CHANGELOG.md"
      - "*CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEVOPS_REPO: "javelin-cloud"
  DEVOPS_BRANCH: "main"
  CICD_TRIGGER: "enable"
  CICD_WORKFLOW: "manual-deploy-ramparts-server.yml"

jobs:
  reusable-vars:
    permissions:
      contents: 'read'
    runs-on: ubuntu-24.04
    steps:
      - name: reusable variables
        run: echo "Exposing env vars"
    outputs:
      CICD_TRIGGER: ${{ env.CICD_TRIGGER }}

  javelin-trigger:
    needs:
      - reusable-vars
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-24.04
    if: (needs.reusable-vars.outputs.CICD_TRIGGER == 'enable')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        run: sudo apt install gh -y

      - name: Trigger private repo workflow
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
        run: |
          gh workflow run ${{ env.CICD_WORKFLOW }} \
            --repo ${{ github.repository_owner }}/${{ env.DEVOPS_REPO }} \
            --ref ${{ env.DEVOPS_BRANCH }}
