name: Release Docker (GHCR)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    name: Build and push multi-arch image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: meta
        run: |
          TAG_REF="${GITHUB_REF##*/}"
          VERSION="${TAG_REF#v}"
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "tag=${TAG_REF}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./MCP-Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.version }}
            ghcr.io/${{ steps.meta.outputs.repo }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print image info
        run: |
          echo "Pushed tags: ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.version }}, latest"
          echo "Pull with: docker pull ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.version }}"

